spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/javadb
spring.datasource.username=postgres
spring.datasource.password=Feli0115
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect